spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs"
  contactDetails:
    name: "Jim L. Oan - QA Lead"
    email: "jim@eazybank.com"
  onCallSupport:
    - (555) 777-7890
    - (555) 777-0987