spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs"
  contactDetails:
    name: "Carrie Code - QA Lead"
    email: "carrie@eazybank.com"
  onCallSupport:
    - (555) 666-7890
    - (555) 666-0987